# INSERT INTO sys_param VALUES(1, CURRENT_DATE, NULL, "DTS", NULL, "XX");

INSERT INTO company VALUES ("0001", "EMEA", "Oscar Wei EMEA region");

INSERT INTO story (PID, NAME, DESCRIPTION, STATUS, USER_CREATED, DATE_CREATED)
VALUES (1, "Story 1", "Story 1 desc", 0, "DTS.Admin", CURRENT_TIMESTAMP);
#
INSERT INTO story_item (PID, NAME, STATUS, PRIORITY, DELAY, PID_STORY, USER_CREATED, DATE_CREATED)
VALUES (1, "Story Item 1", 2, 0, 0, 1, "DTS.Admin", CURRENT_TIMESTAMP);
INSERT INTO story_item (PID, NAME, STATUS, PRIORITY, DELAY, PID_STORY, USER_CREATED, DATE_CREATED)
VALUES (2, "Story Item 2", 3, 1, 2, 1, "DTS.Admin", CURRENT_TIMESTAMP);
INSERT INTO story_item (PID, NAME, STATUS, PRIORITY, DELAY, PID_STORY, USER_CREATED, DATE_CREATED)
VALUES (3, "Story Item 3", 4, 2, 3, 1, "DTS.Admin", CURRENT_TIMESTAMP);
INSERT INTO story_item (PID, NAME, STATUS, PRIORITY, DELAY, PID_STORY, USER_CREATED, DATE_CREATED)
VALUES (4, "Story Item 4", 2, 2, 5, 1, "DTS.Admin", CURRENT_TIMESTAMP);
INSERT INTO story_item (PID, NAME, STATUS, PRIORITY, DELAY, PID_STORY, USER_CREATED, DATE_CREATED)
VALUES (5, "Story Item 5", 3, 3, 0, 1, "DTS.Admin", CURRENT_TIMESTAMP);
INSERT INTO story_item (PID, NAME, STATUS, PRIORITY, DELAY, PID_STORY, USER_CREATED, DATE_CREATED)
VALUES (6, "Story Item 6", 5, 2, 10, 1, "DTS.Admin", CURRENT_TIMESTAMP);
INSERT INTO story_item (PID, NAME, STATUS, PRIORITY, DELAY, PID_STORY, USER_CREATED, DATE_CREATED)
VALUES (7, "Story Item 7", 2, 3, 6, 1, "DTS.Admin", CURRENT_TIMESTAMP);
INSERT INTO story_item (PID, NAME, STATUS, PRIORITY, DELAY, PID_STORY, USER_CREATED, DATE_CREATED)
VALUES (8, "Story Item 8", 3, 2, 4, 1, "DTS.Admin", CURRENT_TIMESTAMP);
INSERT INTO story_item (PID, NAME, STATUS, PRIORITY, DELAY, PID_STORY, USER_CREATED, DATE_CREATED)
VALUES (9, "Story Item 9", 4, 1, 1, 1, "DTS.Admin", CURRENT_TIMESTAMP);
INSERT INTO story_item (PID, NAME, STATUS, PRIORITY, DELAY, PID_STORY, USER_CREATED, DATE_CREATED)
VALUES (10, "Story Item 10", 2, 3, 0, 1, "DTS.Admin", CURRENT_TIMESTAMP);

